# Default values for hellomsa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

services:
  frontendapp:
    name: frontendapp
    image: "bamyam/frontendappc" # Replace with your actual image name
    tag: v2
    port: 3000
    nodeport: 32321

  visitorapp:
    name: visitorapp  
    image: "bamyam/visitorappc" # Replace with your actual image name
    tag: v2
    port: 8000
    nodeport: 32322

  adminapp:
    name: adminapp  
    image: "bamyam/adminappc" # Replace with your actual image name
    tag: v2
    port: 8010
    nodeport: 32323

nginx:
  image: nginx
  tag: latest
