apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    # Nginx configuration for reverse proxy
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    # Nginx configuration for reverse proxy
    server {
       listen 80;
       server_name kimseogeun.com;


       location / {
          proxy_pass http://frontendapp-service:3000/;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
          proxy_set_header X-Forwarded-Prefix /main;
          proxy_set_header X-Forwarded-Uri $uri;
       }
     }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <h1>Hello, ArgoCD!! Hello, GitOps!!</h1>
